#!/bin/bash

# System Information
username="$USER"
datetime="$(date +"%Y-%m-%d %H:%M:%S")"

# System Information
hostname="$(hostname)"
os="$(lsb_release -ds)"
uptime="$(uptime -p)"

# Hardware Information
cpu="$(cat /proc/cpuinfo | grep "model name" | uniq | cut -d ':' -f 2 | sed 's/^[ \t]*//')"
cpu_speed="$(lscpu | grep "CPU MHz" | awk '{print $3}') MHz"
ram="$(free -h | awk '/Mem/ {print $2}')"
disk="$(lsblk -o NAME,MODEL,SIZE --nodeps --noheadings | awk '{print $1, $2, $3}')"
video="$(lspci | grep -i "VGA compatible controller" | awk -F': ' '{print $2}')"

# Network Information
fqdn="$(hostname --fqdn)"
host_address="$(hostname -I | awk '{print $1}')"
gateway_ip="$(ip route | awk '/default/ {print $3}')"
dns_server="$(cat /etc/resolv.conf | awk '/nameserver/ {print $2}')"
interface_name="$(ip addr | awk '/^[0-9]+:/ {print substr($2, 1, length($2)-1)}')"
ip_address="$(ip addr | awk '/inet / && !/127.0.0.1/ {print $2}')"

# System Status
users_logged_in="$(who | awk '{print $1}' | sort -u | tr '\n' ', ')"
disk_space="$(df -h | awk 'NR>1 {print $1, $4}')"
process_count="$(ps -ef | wc -l)"
load_averages="$(cat /proc/loadavg | awk '{print $1", "$2", "$3}')"
memory_allocation="$(free -h | awk '/Mem:/ {print "Total:", $2, "Used:", $3, "Free:", $4}')"
listening_ports="$(netstat -tuln | awk '/^tcp|^udp/ {print $4}')"
ufw_rules="$(ufw show numbered)"

# System Report
echo "System Report generated by $username, $datetime"
echo ""
echo "System Information"
echo "-------------------"
echo "Hostname: $hostname"
echo "OS: $os"
echo "Uptime: $uptime"
echo ""

echo "Hardware Information"
echo "----------------------"
echo "CPU: $cpu"
echo "Speed: $cpu_speed"
echo "RAM: $ram"
echo "Disk(s): $disk"
echo "Video: $video"
echo ""

echo "Network Information"
echo "---------------------"
echo "FQDN: $fqdn"
echo "Host Address: $host_address"
echo "Gateway IP: $gateway_ip"
echo "DNS Server: $dns_server"
echo ""
echo "InterfaceName: $interface_name"
echo "IP Address: $ip_address"
echo ""

echo "System Status"
echo "--------------"
echo "Users Logged In: $users_logged_in"
echo "Disk Space:"
echo "$disk_space"
echo "Process Count: $process_count"
echo "Load Averages: $load_averages"
echo "Memory Allocation: $memory_allocation"
echo "Listening Network Ports: $listening_ports"
echo "UFW Rules:"
echo "$ufw_rules"
